### ISSUE TITLE
Add multer to peer dependencies

### ISSUE THREAD

**Issue by sandervanhooft** [HriBB/graphql-server-express-upload#1]
@HriBB After reading the docs and checking `package.json`, I'd suggest to add `multer` to the peer dependencies.

**Comment by thebigredgeek** [comment]
@sandervanhooft `peerDependencies` are deprecated in npm 3.  I don't think we should add them

**Comment by sandervanhooft** [comment]
Ok, good to know :). Perhaps as a dependency then? It's not included by the
Apollo stack as far as I know.

**Comment by HriBB** [comment]
We can add it as a `dependency`. Again, want to make a PR? Otherwise I will fix this next week ... hopefully :)

**Comment by sandervanhooft** [comment]
I'm using `"multer": "^1.2.0"`, will try to make a PR soon

**Comment by thebigredgeek** [comment]
I honestly dont know if adding it as a dependency is the correct approach, unless we also bind the middleware ourselves within the apollo upload middleware.  That might actually be the ideal solution here
