### ISSUE TITLE
bodyParser.json

### ISSUE THREAD

**Issue by sandervanhooft** [HriBB/graphql-server-express-upload#3]
Hi @HriBB ,

I'm not sure about the following. Any suggestion?

The [Apollo Server Express](https://github.com/apollostack/graphql-server) setup suggests to use `bodyParser.json()`:
```
app.use('/graphql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));
```

[Your suggested setup ](https://github.com/HriBB/graphql-server-express-upload/blob/master/README.md)makes no note of `bodyParser.json()`:
```
app.use('/graphql',
  upload.array('files'),
  // after multer and before graphqlExpress
  graphqlExpressUpload({ endpointURL: '/graphql' }),
  graphqlExpress((req) => {
    return {
      schema,
      context: {}
    }
  })
)
```

As you suggest that order is important: where should I put `bodyParser.json()`?

**Comment by thebigredgeek** [comment]
@sandervanhooft you can put `bodyParser.json()` anywhere above `graphqlExpress((req) => ... )`

@HriBB we should probably update the docs :p

**Comment by HriBB** [comment]
Want to make a PR?

**Comment by sandervanhooft** [comment]
Done.

**Comment by sandervanhooft** [comment]
I'm using `"body-parser": "^1.15.2",`, will try to make an additional PR soon.

**Comment by HriBB** [comment]
Closing issue. Feel free to reopen if needed.
